apiVersion: v1
kind: Service
metadata:
  name: image-processing
spec:
  selector:
    app: image-processing
    tier: backend
    asghar: akbar
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

